
dist: trusty

sudo: required

language: python

python:
  - "2.7"
<<<<<<< HEAD
  # - "3.5"
  # - "3.6"
  # - "pypy-5.7.1" # PyPy cannot be tested right now because florence uses scipy.io HDF5 readers/writers
=======
  - "3.5"
  - "3.6"
  # - "pypy-5.7.1"
>>>>>>> upstream/master

branches:
  only:
    master


# Install dependencies
before_install:
  - FLORENCEPATH=$(pwd)
  - echo $FLORENCEPATH
  - sudo apt-get update --fix-missing
  # Install BLAS libraries
  - echo -ne '\n' | sudo apt-get install gfortran libblas-dev liblapack-dev libatlas-base-dev libopenblas-* libsuitesparse-dev swig
  # pypi packages - install before installing PostMesh
  - cd $FLORENCEPATH
  - travis_wait 50 pip install -r "requirements.txt"
  # Install Eigen
  - cd ~
  - wget http://bitbucket.org/eigen/eigen/get/3.3.3.tar.bz2
  - tar -xvf 3.3.3.tar.bz2
  - sudo mv eigen-eigen-67e894c6cd8f /usr/local/include/eigen/
  # Install OpenCascade
  - echo -ne '\n' | sudo apt-get install liboce-*
  # PostMesh
<<<<<<< HEAD
  - cd ~
  - git clone https://github.com/romeric/PostMesh
  - cd PostMesh/PostMeshPy
  - python setup.py build_ext && python setup.py bdist_wheel
  - cd .. && pip install PostMeshPy/dist/*.whl
  - cd .. && rm -rf PostMesh
=======
  - pip install PostMeshPy
>>>>>>> upstream/master
  # Fastor
  - git clone https://github.com/romeric/Fastor
  - sudo mv Fastor /usr/local/include/Fastor/
  # update the cache
  - sudo ldconfig

install:
  # build florence modules
<<<<<<< HEAD
  - cd $FLORENCEPATH; python setup.py build
=======
  - cd $FLORENCEPATH; echo -ne '\n' | python setup.py build
>>>>>>> upstream/master

script:
  # Run florence test suite
  - cd ~
  - export PYTHONPATH=$FLORENCEPATH:$PYTHONPATH
  - cd $FLORENCEPATH/tests; nosetests -x --with-coverage --cover-package=Florence test.py

after_success:
  - coveralls

notifications:
  email: false
